book_loaning_app/config/routes.rb
Rails.application.routes.draw do

  resources :authors, only: [:index, :show]
  resources :loans, only: [:new, :create, :index]
  resources :books
  root 'welcome#show'
  resources :users

  resources :books do 
    resources :loans, only: [:new, :index]
    resources :comments, only: [:new, :create, :index, :show]
  end

  resources :comments do
    resources :replies
  end

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'

  resources :books do
    get 'return', on: :member
  end

  resources :users do
    get 'lending', on: :member
  end
  
  resources :users do
    resources :books, only: [:index]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_loaning_app/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    has_many :replies
    validates :title, presence: :true
    validates :body, presence: :true
end

book_loaning_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @book = Book.find(params[:book_id])
        @comment = Comment.new(user_id: current_user.id, book_id: @book.id)
    end

    def create
        @comment = Comment.new(comment_params)
        @book = Book.find(params[:book_id])
        if @comment.save
            redirect_to book_path(@book)
        else
            @errors = @comment.errors
            render new_comment_path(@comment)
        end
    end

    def show
        @book = Book.find(params[:book_id])
        @comment = Comment.find(params[:id])
        if @comment.book == @book
            
            respond_to do |format|
                format.html
                format.json {render json: @comment}
            end
        else
            render status: 404
        end
    end

    def index
        @comments = Comment.where(book_id: params[:book_id])
        render json: @comments
    end


    private

    def comment_params
        params.require(:comment).permit(:book_id, :user_id, :title, :body)
    end

end

book_loaning_app/app/helpers/comments_helper.rb
module CommentsHelper
end

book_loaning_app/app/views/comments/_form.html.erb
<h4>Add A Review</h4>

<%if @errors%>
<%="Sorry, your review could not be created because:"%><br>
    <%@errors.full_messages.each do |e|%>
        <li><%=e%></li>
    <%end%>
<%end%>

<%=form_for [book, comment] do |f|%>
<%=f.label :title%><br>
<%=f.text_field :title, size: 60%><br>
<%=f.label :body, "Review"%><br>
<%=f.text_area :body, placeholder: "Share your thoughts...", cols: 60, rows: 10%><br>

<%=f.hidden_field :user_id%>
<%=f.hidden_field :book_id%>
<%=f.submit "Submit"%>
<%end%>

book_loaning_app/app/views/comments/index.html.erb
<%@comments.each do |comment|%>
<%=comment.title%>
<%end%>

book_loaning_app/app/views/comments/new.html.erb
<%= render partial: 'form', locals: {book: @book, comment: @comment} %>

book_loaning_app/app/views/comments/show.html.erb
<p>Review of: <samp class="comment_book"><%=@comment.book.title%></samp></p>
<p>By: <samp class="comment_user"><%=@comment.user.username%></samp></p>
<h2 class="comment_title"><%=@comment.title%></h2>
<p class="comment_body"><%=@comment.body%></p>
<a href="#" class="js-prev">Prev</a>

<a href="#" class="js-next" data-bookid="<%=@comment.book.id%>" data-commentid="<%=@comment.id%>">Next</a>

<h3>Replies</h3>
<div class="initial_replies"><ul>
    <%@comment.replies.each do |reply|%>
        <li><%=reply.user.username%> says: <%=reply.body%></li>
    <%end%>
</ul></div>

<div class="comment_replies">
    <ul></ul>
</div>

<%=link_to "Add a reply", new_comment_reply_path(@comment)%>
<%=render partial: "replies/form", locals: {reply: Reply.new(comment_id: @comment.id, user_id: current_user.id), comment: @comment}%>