book_loaning_app/config/routes.rb
Rails.application.routes.draw do

  resources :authors, only: [:index, :show]
  resources :loans, only: [:new, :create, :index]
  resources :books
  root 'welcome#show'
  resources :users

  resources :books do 
    resources :loans, only: [:new, :index]
    resources :comments, only: [:new, :create, :index, :show]
  end

  resources :comments do
    resources :replies
  end

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'

  resources :books do
    get 'return', on: :member
  end

  resources :users do
    get 'lending', on: :member
  end
  
  resources :users do
    resources :books, only: [:index]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_loaning_app/app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    has_many :users, through: :books
    
    validates :name, presence: true

    def self.search(query)
        self.where("name LIKE :query", {query: "%#{query}%"})
    end

end

book_loaning_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


    def index
        @authors = Author.search(params[:query])
        render 'index'
    end

    def show
        @author = Author.find(params[:id])
        respond_to do |format|
            format.html
            format.json {render json: @author, status: 200}
        end
    end

end

book_loaning_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

book_loaning_app/app/views/authors/_authors.html.erb
<%authors.each do |author|%>
    <%=link_to author.name, author_path(author)%>
    <%="-- #{author.books.count} books in libraries"%><br>
<%end%>

book_loaning_app/app/views/authors/index.html.erb
<h2>Authors</h2>

<%= form_tag authors_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query], placeholder: "Search by name" %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<%= render partial: 'authors', locals: {authors: @authors}%>

book_loaning_app/app/views/authors/show.html.erb
<h2><%=@author.name%></h2>
<ul>
    <%@author.books.each do |book|%>
        <li><%=link_to book.title, book_path(book)%>
        owned by: <%=link_to book.user.username, user_path(book.user)%>
        <%="(Loaned)" unless !book.loaned?%></li>
    <%end%>
</ul>