book_loaning_app/config/routes.rb
Rails.application.routes.draw do

  resources :authors, only: [:index, :show]
  resources :loans, only: [:new, :create, :index]
  resources :books
  root 'welcome#show'
  resources :users

  resources :books do 
    resources :loans, only: [:new, :index]
    resources :comments, only: [:new, :create, :index, :show]
  end

  resources :comments do
    resources :replies
  end

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'

  resources :books do
    get 'return', on: :member
  end

  resources :users do
    get 'lending', on: :member
  end
  
  resources :users do
    resources :books, only: [:index]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_loaning_app/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :books
    has_many :loans, through: :books
    has_many :authors, through: :books
    has_many :comments
    has_many :replies
    
    validates :username, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, too_short: " must be at least 6 characters" }



end

book_loaning_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show, :index]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def index
        @users = User.all 
    end

    def lending
        @user = User.find(params[:id])
        @loans = Loan.books_i_am_loaning(@user)
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

book_loaning_app/app/helpers/users_helper.rb
module UsersHelper

    def user_header
        if @user == current_user
           "Welcome #{@user.username}!"
        else
            "#{@user.username}'s Page"
        end
    end
end

book_loaning_app/app/views/users/_errors.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(user.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

book_loaning_app/app/views/users/_form.html.erb
<%=form_for user do |f|%>
    <%=f.label :username%>
    <%=f.text_field :username%><br>
    <%=f.label :password%>
    <%=f.password_field :password%><br>
    <%=f.label :password_confirmation%>
    <%=f.password_field :password_confirmation%>
    <%=f.submit%>
<%end%>

book_loaning_app/app/views/users/index.html.erb
<%@users.each do |user|%>
    <%=user.username%><br>
<%end%>

book_loaning_app/app/views/users/lending.html.erb
<%@loans.each do |loan|%>
<%= loan.book.title %>
<%end%>

book_loaning_app/app/views/users/new.html.erb
<h1>Create New User Form</h1>
<%= render partial: "errors", locals: {user: @user} %>
<%= render partial: "form", locals: {user: @user} %>

book_loaning_app/app/views/users/show.html.erb
<h2><%=user_header%></h2><br>

<h3>Recently Added Books</h3>
<%Book.last_five(@user).each do |book|%>
    <li><%=link_to book.title, book_path(book)%>
    <%="(Loaned)" if book.loaned?%></li>
<%end%><br>

<p>
    <%= link_to "All Books", user_books_path(@user), class: "load_books"%>
<%= link_to "Add a Book", new_book_path unless @user != current_user%></p>


<h3>Authors</h3>
<%@user.authors.uniq.each do |author|%>
    <li><%=link_to author.name, author_path(author)%></li>
<%end%>

<h3>Books I'm Borrowing</h3>
<%Loan.loaned_to_me(@user).each do |loan|%>
    <%=link_to loan.book.title, book_path(loan.book) if loan.book%>
<%end%>

<h2>Live Coding</h2>
<button class="alphabetize_books" href="<%=user_books_path(@user)%>">Alphabetize Books</button>
<div class="alphabetized_books"><ul></ul></div>