book_loaning_app/config/routes.rb
Rails.application.routes.draw do

  resources :authors, only: [:index, :show]
  resources :loans, only: [:new, :create, :index]
  resources :books
  root 'welcome#show'
  resources :users

  resources :books do 
    resources :loans, only: [:new, :index]
    resources :comments, only: [:new, :create, :index, :show]
  end

  resources :comments do
    resources :replies
  end

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'

  resources :books do
    get 'return', on: :member
  end

  resources :users do
    get 'lending', on: :member
  end
  
  resources :users do
    resources :books, only: [:index]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book_loaning_app/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :author, optional: true
    has_many :loans
    has_many :genres
    has_many :comments

    validates :title, presence: true
    
    accepts_nested_attributes_for :genres, reject_if: :all_blank

    
    def author_attributes=(author)
        self.author = Author.find_or_create_by(name: author)
        self.author.save
    end

    def loaned_to 
        Loan.where(book_id: self.id, returned: false)
    end
    
    def loaned?
        loaned_to != [] ? true : false
    end

    def currently_loaned_to
        if self.loaned?
            borrower_id = self.loaned_to.pluck(:borrower_id)[0]
            borrower = User.find(borrower_id)
            borrower.username
        end
    end

    def self.last_five(user)
        where("user_id = ?", user.id).order(created_at: :desc).take(5)
    end

    def self.search(query)
        self.where("title LIKE :query", {query: "%#{query}%"})
    end

    def author?
        self.author == nil ? "" : self.author.name
    end
end

book_loaning_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :require_login, only: [:new, :edit, :destroy]
    

    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            @books = Book.search(params[:query]).where(user_id: @user.id)
            respond_to do |format|
                format.html
                format.json {render json: @books}
            end
        else
            @books = Book.search(params[:query])
        end
    end
    
    def new
        @book = Book.new
        build_genres
    end

    def create
        @book = Book.new(book_params)
        @book.author_attributes = (params[:book][:author])
        @book.user = current_user
        book_save?
    end

    def show
        @book = Book.find(params[:id])
        respond_to do |format|
            format.html
            format.json {render json: @book}
        end
    end

    def edit
        @book = Book.find(params[:id])
        build_genres
        redirect_if_not_book_owner
    end

    def update
        @book = Book.find(params[:id])
        redirect_if_not_book_owner
        @book.author_attributes = (params[:book][:author])
        @book.update(book_params)
        book_save?
    end

    def destroy
        @book = Book.find(params[:id])
        redirect_if_not_book_owner
        @book.destroy
        redirect_to user_path(current_user)
    end

    def return 
        @book = Book.find(params[:id])
        @loan = Loan.find_by(book_id: @book.id, returned: false)
        return_book_or_redirect
    end


    private

    def book_params
        params.require(:book).permit(:title, :description,
            genres_attributes: [:id, :name])
    end
    
    def redirect_if_not_book_owner
        if @book.user != current_user
            flash.alert = "You are not the owner of this book."
            redirect_to book_path(@book)
        end
    end

    def build_genres
        count = 0
        if params[:book] != nil
            genres = params[:book][:genres_attributes]
            genres.each do |g, h|
                h.each do |h, k|
                    if k!= ""
                        count = count + 1
                    end
                end
            end
        end
        num_genres = @book.genres.count
        num = 3 - count - num_genres
        num.times do 
            @book.genres.build 
        end
    end

    def book_save?
        if @book.save
            redirect_to book_path(@book)
        else
            build_genres
            render new_book_path
        end
    end

    def return_book_or_redirect
        if @loan.borrower_id != current_user.id
            flash.alert = "You have not borrowed this book."
            redirect_to book_path(@book)
        else
            @loan.returned = true
            @loan.save
            redirect_to book_path(@book)
        end
    end

    end

book_loaning_app/app/helpers/books_helper.rb
module BooksHelper

    def book_loan_links
        if @book.loaned? && @book.currently_loaned_to != current_user.username
            link_to "Loaned to #{@book.currently_loaned_to}", user_path(User.find_by(username: @book.currently_loaned_to))
        elsif @book.currently_loaned_to == current_user.username
            link_to "Return Book", return_book_path(@book)
        elsif !@book.loaned? && @book.user == current_user
            link_to "Loan Book", new_book_loan_path(@book)
        end
    end

end

book_loaning_app/app/views/books/_errors.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(book.errors.count, "error") %>
      prohibited this book from being created:
    </h2>
 
    <ul>
    <% book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

book_loaning_app/app/views/books/_form.html.erb
<%= form_for book do |f| %>
    <%=f.label :title %>
    <%=f.text_field :title %><br>

    Author<%= f.text_field :author, list: "authors_autocomplete", value: book.author? %>
    <datalist id="authors_autocomplete">
    <% Author.all.each do |author| %>
        <option value="<%= author.name%>">
    <% end %>
    </datalist><br>

    <%=f.fields_for :genres do |g|%>
    Genre<%=g.text_field :name %><br>
    <%end%>

    <%=f.label :description%>
    <%=f.text_area :description%><br>

    <%=f.submit "Submit"%>
<%end%>

book_loaning_app/app/views/books/_query.html.erb
<%if user%>
    <%= form_tag user_books_path(user), method: :get do%>
    <p>
        <%= text_field_tag :query, params[:query], placeholder: "Search by title" %>
        <%= submit_tag "Search", name: nil %>
    </p>
    <%end%>
<%else%>
    <%= form_tag books_path, method: :get do %>
    <p>
        <%= text_field_tag :query, params[:query], placeholder: "Search by title" %>
        <%= submit_tag "Search", name: nil %>
    </p>
    <% end %>
<%end%>

book_loaning_app/app/views/books/edit.html.erb
<%= render partial: "form", locals: {book: @book} %>

book_loaning_app/app/views/books/index.html.erb
<h3>Books</h3>
<%=render partial: 'query', locals: {book: @book, user: @user} %>
<%@books.each do |book| %>
    <%= link_to book.title, book_path(book) %><br>
<%end%>

book_loaning_app/app/views/books/new.html.erb
<h2>Add A Book Here</h2>
<%= render partial: "errors", locals: {book: @book}%>
<%= render partial: "form", locals: {book: @book} %>

book_loaning_app/app/views/books/show.html.erb
<h2><%= @book.title %></h2><br>
By: <%= link_to @book.author.name, author_path(@book.author) unless @book.author == nil%><br>
Description: <%= @book.description%><br>
Genre Tags: <%=@book.genres.pluck(:name).join(", ")%><br>
Owner: <%=link_to @book.user.username, user_path(@book.user)%><br>

<%=link_to "Loan History", book_loans_path(@book)%><br>

<%= book_loan_links %><br>

<%if @book.user == current_user%>
    <%= link_to "Edit Book Information", edit_book_path(@book)%>
    <%= link_to "Delete Book", @book, method: :delete %>
<%end%>

<% if @book.comments%>
    <h3>Reviews</h3>
    <div class="all_comments"><ol></ol></div>
<%end%><br>
<%= render partial: 'comments/form', locals: {comment: Comment.new(book_id: @book.id, user_id: current_user.id), book: @book}%>